### ISSUE TITLE
(FakeTimer): No way to sense microtasks like sinonjs/fake-timers

### ISSUE THREAD

**Issue by LumaKernel** [udibo/mock#14]
No methods like `clock.runMicrotasks()` in https://github.com/sinonjs/fake-timers.

I cannot test like following.

```ts
import { assertEquals } from "https://deno.land/std@0.108.0/testing/asserts.ts#^";
import type { Spy } from "https://deno.land/x/mock@0.10.1/spy.ts";
import { spy } from "https://deno.land/x/mock@0.10.1/spy.ts";
import { FakeTime } from "https://deno.land/x/mock@0.10.1/time.ts";

const wait = (ms: number) => {
  return new Promise((resolve, reject) => {
    if (ms > 10000) return reject(new Error("Can't wait so long!!!"));
    setTimeout(resolve, ms);
  });
};

Deno.test("wait", () => {
  const time: FakeTime = new FakeTime();

  try {
    main();
  } finally {
    time.restore();
  }

  function main() {
    const ok: Spy<void> = spy();
    const ng: Spy<void> = spy();
    wait(500).then(ok).catch(ng);

    assertEquals(ok.calls.length, 0);
    assertEquals(ng.calls.length, 0);

    time.tick(1000);
    // no way to consume all microtaks!

    assertEquals(ok.calls.length, 1); // FAIL
    assertEquals(ng.calls.length, 0);
  }
});
```

## Workaround

I'm using following as trigger. Or is it correct way to do so?

```ts
// ...
  const nativeSetTimeout = setTimeout;
  const runMicrotasks = () => {
    return new Promise((resolve) => nativeSetTimeout(resolve, 0));
  };
// ...
```

Note that `await 0;` is not enough because it only consumes currently queued microtasks.

<details>
<summary>full</summary>

```ts
import { assertEquals } from "https://deno.land/std@0.108.0/testing/asserts.ts#^";
import type { Spy } from "https://deno.land/x/mock@0.10.1/spy.ts";
import { spy } from "https://deno.land/x/mock@0.10.1/spy.ts";
import { FakeTime } from "https://deno.land/x/mock@0.10.1/time.ts";

const wait = (ms: number) => {
  return new Promise((resolve, reject) => {
    if (ms > 10000) return reject(new Error("Can't wait so long!!!"));
    setTimeout(resolve, ms);
  });
};

Deno.test("wait", async () => {
  const nativeSetTimeout = setTimeout;
  const runMicrotasks = () => {
    return new Promise((resolve) => nativeSetTimeout(resolve, 0));
  };
  const time: FakeTime = new FakeTime();

  try {
    await main();
  } finally {
    time.restore();
  }

  async function main() {
    const ok: Spy<void> = spy();
    const ng: Spy<void> = spy();
    wait(500).then(ok).catch(ng);

    assertEquals(ok.calls.length, 0);
    assertEquals(ng.calls.length, 0);

    time.tick(1000);
    await runMicrotasks();

    assertEquals(ok.calls.length, 1);
    assertEquals(ng.calls.length, 0);
  }
});
```

</details>

**Comment by KyleJune** [comment]
For workaround, you could import delay from time.ts, then do `await delay(0)` instead of creating and awaiting your runMicrotasks function. The delay exported from time.ts uses native time. Looks like I missed exporting that function from mod.ts, I'll update mod.ts to export that like time.ts does.

Another option would be to create a variable for your wait call's returned promise, then after the time.tick call, await the promise so that the test doesn't continue until that promise resolves.

If it would make it easier to work with, I'd be fine with adding a time.runMicrotasks function. I think it would just need to do `await delay(0)`.

**Comment by LumaKernel** [comment]
Hmmm... I noticed that `clock.runMicrotasks()` in shinon/fake-timers is mocking `process.nextTick` but it is not function for microtask enqueue.

```js
// node.js
queueMicrotask(()=>console.log(1));
process.nextTick(()=>console.log(2));  // node.js specific
```

Above will be swapped. ( 2 -> 1 ). It's maybe shinon/fake-timers 's mistaken naming for `clock.runMicrotasks`...

hm... at first, it is not needed to mock microtasks because they are not real-time related, so we should not wait long time for microtasks.

How about adding `tickAsync()` instead? `tickAsync` in shinon/fake-timers is a real consumer for microtasks.

https://github.com/sinonjs/fake-timers/blob/679214eb0aa6702b65162608bb117b83f04947fe/src/fake-timers-src.js#L1332-L1342

**Comment by KyleJune** [comment]
queueMicrotask and process.nextTick have different behavior in nodejs. queueMicrotask has the same behavior as setTimeout with a time of 0, it adds the callback to the end of the queue of microtasks to do next. process.nextTick puts the callback at the front of that same queue which is why you find that the process.nextTick callback gets called before the queueMicrotask callback. If you were to add another process.nextTick call, you would find that the later one gets called before the first one.

I agree with the idea to add tickAsync and runMicrotasks functions. awaiting tickAsync() should resolve once all queued microtasks are completed. runMicrotasks should just call await delay(0) so that all microtasks already in the queue will be completed. I believe this will likely require refactoring now and tick, not sure when I will have time to work on it but I'll leave this task open for it.

I'll create separate issues for each change and close this one in favor of them.

**Comment by KyleJune** [comment]
For now you can import delay from time.ts to be able to replicate the behavior of runMicrotasks. Once implemented, runMicrotasks and tickAsync should resolve your issues.

**Comment by LumaKernel** [comment]
> queueMicrotask has the same behavior as setTimeout with a time of 0

`queueMicrotask(cb)` and `setTimeout(cb, 0)` are different. They have different queues. `queueMicrotask(cb)` is like `Promise.resolve().then(cb)`


```js
// node.js
queueMicrotask(() => console.log('qm1'));
Promise.resolve().then(() => console.log('ps1'));
setTimeout(() => console.log('st1'), 0)
process.nextTick(() => console.log('nt1'))

queueMicrotask(() => console.log('qm2'));
Promise.resolve().then(() => console.log('ps2'));
setTimeout(() => console.log('st2'), 0)
process.nextTick(() => console.log('nt2'))
```

The output is 

```
nt1
nt2
qm1
ps1
qm2
ps2
st1
st2
```

The order of output is guaranteed.

**Comment by KyleJune** [comment]
I guess I was wrong regarding queueMicrotask having the same behavior as setTimeout(() => ..., 0). tickAsync should have delays before each timeout to ensure all queued microtasks are executed before the timers. I'll update the issue for that.

**Comment by LumaKernel** [comment]
To summarize it up, there are 3 queues ( in `deno`, 2 queues ), _nextTick_, _microtask_ (for Promise), _task_ (for setTimeout).
_nextTick_ always precedes _microtask_, and _microtask_ always precedes _task_.
Enqueued callbacks in that turn, they also precede to next level queue.

```js
queueMicrotask(() => console.log('qm1'));
Promise.resolve().then(() => console.log('ps1'));
setTimeout(() => console.log('st1'), 0);
process.nextTick(() => console.log('nt1'));

queueMicrotask(() => console.log('qm2'));
queueMicrotask(() => queueMicrotask(() => console.log('qm22')));
Promise.resolve().then(() => console.log('ps2'));
setTimeout(() => console.log('st2'), 0);
process.nextTick(() => console.log('nt2'));
process.nextTick(() => process.nextTick(() => console.log('nt22')));
```

```
nt1
nt2
nt22
qm1
ps1
qm2
ps2
qm22
st1
st2
```

**Comment by KyleJune** [comment]
@LumaKernel I've improved FakeTime controls, it will be available in the next release. I plan on publishing it tomorrow after I resolve one more issue unrelated to FakeTime.
