### ISSUE TITLE
Stubbing fetch fails after upgrade to v0.12.0

### ISSUE THREAD

**Issue by paambaati** [udibo/mock#24]
This has left me stumped, but somehow, [after upgrading to v0.12.0](https://github.com/getoslash/chrome-webstore-cli/pull/5), mocking `fetch` on `globalThis` seems to fail. See failing test run – https://github.com/getoslash/chrome-webstore-cli/runs/4287269860?check_suite_focus=true

You can see that on the previous versions, the tests pass fine.

One failing test – https://github.com/getoslash/chrome-webstore-cli/blob/26e037061f286f6848240368e86acd3036d4dd62/tests/helpers.api.test.ts#L171-L309

**Comment by KyleJune** [comment]
There was a change to the stub function to make it possible to stub non function properties. 

https://github.com/udibo/mock/pull/22

In the example below from your test, stub is now making fetch an array instead of making it a function that returns values from the array.

```ts
const fetchStub: Stub<typeof globalThis> = stub(globalThis, "fetch", [
      Promise.resolve(
        new Response(
          new Blob([
            JSON.stringify(
              {
                "access_token": "xyz",
              },
              null,
              2,
            ),
          ], { type: "application/json" }),
        ),
      ),
      Promise.resolve(
        new Response(
          new Blob([
            JSON.stringify(
              {
                "UPLOAD_STATE": "SUCCESS",
              },
              null,
              2,
            ),
          ], { type: "application/json" }),
        ),
      ),
      Promise.resolve(
        new Response(
          new Blob([
            JSON.stringify(
              {
                "access_token": "xyz",
              },
              null,
              2,
            ),
          ], { type: "application/json" }),
        ),
      ),
      Promise.resolve(
        new Response(
          new Blob([
            JSON.stringify(
              {
                "status": ["OK"],
              },
              null,
              2,
            ),
          ], { type: "application/json" }),
        ),
      ),
    ]);
 ```
 
There are 2 new callbacks available for getting equivalent behavior. returnsNext and resolvesNext. If you use resolvesNext, you can also get rid of the Promise.resolve wrappers, it will return a promise for getting each value from the array.

```ts
const fetchStub: Stub<typeof globalThis> = stub(globalThis, "fetch", resolvesNext([
        new Response(
          new Blob([
            JSON.stringify(
              {
                "access_token": "xyz",
              },
              null,
              2,
            ),
          ], { type: "application/json" }),
        ),
        new Response(
          new Blob([
            JSON.stringify(
              {
                "UPLOAD_STATE": "SUCCESS",
              },
              null,
              2,
            ),
          ], { type: "application/json" }),
        ),
        new Response(
          new Blob([
            JSON.stringify(
              {
                "access_token": "xyz",
              },
              null,
              2,
            ),
          ], { type: "application/json" }),
        ),
        new Response(
          new Blob([
            JSON.stringify(
              {
                "status": ["OK"],
              },
              null,
              2,
            ),
          ], { type: "application/json" }),
        ),
    ]));
```

**Comment by paambaati** [comment]
@KyleJune Thanks for the very detailed response, this fixes it (see https://github.com/getoslash/chrome-webstore-cli/pull/5/commits/c8ed8b4bc34e7f217f2d903e0a6ba3e790b28c89)

Although, I'm curious, is there a specific reason for using generators here? Why not use an array of promises instead?

**Comment by KyleJune** [comment]
I have returnsNext and resolvesNext use generators internally so that any iterable can be passed to it. I suggested using resolvesNext just because it will resolve your values without you having to wrap each of them. You could still wrap each value with Promise.resolve() if you wanted to. If you did that, both returnsNext and resolvesNext would behave the same for the array of promises.

Because these functions accept any iterables, you could make a stub callback return values generated when your stub function is called.

From the following MDN article, if you passed the generator to the returnsNext function, it will return a callback that will return next value on each call. Instead of having to know how many times your stub will be called and declaring an array of all the values it will return, you could make a generator for your stub to use.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator#an_infinite_iterator

**Comment by KyleJune** [comment]
@paambaati I just looked at your code, you shouldn't have to pass in a generator. You should be able to skip creating your `responses` generator and instead just pass `mockResponses` array directly to `resolvesNext` like `resolvesNext(mockResponses)`. 

I've just realized I forgot to add Iterable as an option for resolvesNext. I'll look into fixing that soon so that you won't need to create a generator just to be able to make use of resolvesNext.

**Comment by paambaati** [comment]
@KyleJune Thanks a lot, I figured it had to do with incomplete types. Take your time!

**Comment by KyleJune** [comment]
@paambaati I've fixed the issue with resolvesNext and improved the examples in the readme.

https://github.com/udibo/mock/releases/tag/0.12.1
