### ISSUE TITLE
How to stub Deno namespace

### ISSUE THREAD

**Issue by andrewmclagan** [udibo/mock#4]
How would one go about stubbing methods called in the `Deno` namespace?

e.g. running a cli task:

```typescript
const run = stub(Deno, "run");
```

**Comment by KyleJune** [comment]
Looking at the documentation for [Deno.run](https://doc.deno.land/https/github.com/denoland/deno/releases/latest/download/lib.deno.d.ts#Deno.run), it looks like it is expected to return a Process. Depending on what you are testing, you could either add an array containing a fake process object you would like to be returned for each call to the run function in that test or you could add a function argument that would return a fake process object for each call made to `Deno.run`.

For the fake process object, you would just need to implement the parts that are used by the code you are testing. Documentation for that object can be found [here](https://doc.deno.land/https/github.com/denoland/deno/releases/latest/download/lib.deno.d.ts#Deno.Process).

If all you needed to access on the process object was the pid and you were calling the function once, you could do the following. 

```ts
const run = stub(Deno, "run", [{pid:5}])
try {
  // code you need to test
} finally {
  run.restore();
}
```

If you were calling it multiple times and you needed each fake process to have a different pid, you could instead do the following. In the below example, the first fake process object would have a pid of 5, then the next would have a pid of 6.

```ts
let i = 5;
const run = stub(Deno, "run", () => ({pid:i++}))
try {
  // code you need to test
} finally {
  run.restore();
}
```

Any property you access or method you call on the process object in the code you are testing would need to be implemented.

**Comment by andrewmclagan** [comment]
thanks!

**Comment by abetaev** [comment]
@KyleJune i did same intuitively at first, but it resulted in error
```
SpyError: cannot redefine property
    at spy (https://deno.land/x/mock@v0.10.0/spy.ts:134:13)
    at stub (https://deno.land/x/mock@v0.10.0/stub.ts:32:25)
    ...
```
i don't know what have changed over a year, but definitely there was something
excerpt from my code:
```typescript
import { stub } from "https://deno.land/x/mock@v0.10.0/stub.ts";
// ...
    const s = stub(Deno, "run", [{}]) // <-- this line fails
```
unfortunately this approach is the only i was able to google.
```
deno 1.11.5 (release, x86_64-apple-darwin)
v8 9.1.269.35
typescript 4.3.2
```

**Comment by KyleJune** [comment]
@abetaev I think I was wrong at the time I made my comment. My comment was about stubbing in general. The SpyError is caused by the fact that the Deno namespace was frozen. In the most recent release, 1.12.0, they have decided to unfreeze it. If you upgrade deno you should be able to stub Deno.run now.

https://deno.com/blog/v1.12#deno-namespace-is-now-unfrozen-and-configurable

If they didn't make that change, there were a few ways to work around it.

In time.ts I had to mock the real setTimeout/clearTimeout functions which my module overwrites. To do that, I copied those functions onto an object called NativeTime and have my module call the functions on that object instead of the global ones. That makes it possible for my tests to stub the real functions.

In another module of mine, I needed to stub Deno.test for my TestSuite class that uses it. To do that, I made a static class method called [registerTest](https://github.com/udibo/test_suite/blob/30d204e918c116d2e2153cbc4365c5ecf681660f/test_suite.ts#L181) that just calls through to Deno.test and have the class use that instead of calling Deno.test directly. In the tests where I need to stub Deno.test, I would instead stub TestSuite.registerTest.

**Comment by abetaev** [comment]
@KyleJune thank you for these news :) i'll try it out

i was thinking about modifying code to make it testable, but code in its current form appears to be much simpler than it would be in testable form, so for now i just paused with this activity
