### ISSUE TITLE
Request for a new release with the mod.ts file

### ISSUE THREAD

**Issue by jameskerr** [udibo/mock#5]
It looks like `deno.land/x` just changed the default version (if none was specified) from the master branch to the latest release. I'd love to continue using the `mod.ts` file in the master branch, but it looks like it's not in a release yet. 

Thanks for making this! And isn't Deno great!?

**Comment by KyleJune** [comment]
Sorry about that, I forgot v0.3.0 didn't have the mod.ts file in it. I've added v0.3.1 tag.
I'm close to having v0.4.0 done, I think I'll probably finish it this weekend. It will add the ability to mock time and I'm going to make some changes so this code will pass deno lint. I had this project on hold because of a bug in deno related to timers. I resolved that issue in deno v1.2.0.

**Comment by jameskerr** [comment]
Thanks @KyleJune!
